### PR TITLE
Add ANGLE backend option (macOS)

### PR DESCRIPTION
**Pull request by GameParrot**
Adds an option to the profile editor to control if angle uses the OpenGL or Metal backend.

### CODE REVIEW

**Comment by GameParrot** [comment]
Should the changes also be made to the qt6 branch (I know qt6 is not used in the macOS version at the time.)

**Comment by ChristopherHX** [comment]
> Should the changes also be made to the qt6 branch

Yes, the qt5 ui is on the end of its lifespan and will soon be frozen. I have one technical problem, qt6.2 is not available as binary for macOS 10.14 (only source build support), so cannot test any qt6 builds myself without compiling the whole framework.

**Comment by GameParrot** [comment]
I was able to get QT 6 working by using `brew install qt@6` on macOS Monterey. It is impossible to close the game log in qt6 on macOS.

**Comment by GameParrot** [comment]
I made the changes for qt6 in my qt6 branch. I also fixed the game log closing issue by adding a close button.

**Comment by GameParrot** [comment]
Closes minecraft-linux/mcpelauncher-manifest#768

**Comment by ChristopherHX** [comment]
I prefer to make metal opt in due to blackscreen bugs.

> I also fixed the game log closing issue by adding a close button.

What happens if you remove the `modality: Qt.WindowModal` or `flags: Qt.Dialog` from the windows with a missing close button? So the UI looks similar on linux and macOS, instead of adding a custom button.

**Comment by ChristopherHX** [comment]
To reproduce a black screen you need a macOS 10.10 or 10.12 dmg file built outside of my osx-packaging-scripts repo and run it on macOS 10.14 (possible newer works too). macOS 10.12 systems are not affected, because it never tries to use metal.

**Pull request merged**
