### PR TITLE
Launcher Redesign (qt5)

### PR DESCRIPTION
**Pull request by ChristopherHX**
Test build

### CODE REVIEW

**Comment by ChristopherHX** [comment]
- qt5.9 settings missized
image

- some buttons have len 0
image

- manual updater popop broken, revert qt6 change

**Comment by devendrn** [comment]
I'll try testing the components on qt5 individually to identify the issue and fix it.

**Comment by ChristopherHX** [comment]
If your qt5.x is newer than 5.9, like in ubuntu 22.04 only the 3rd issue remains.
These are certainly workarounds for old qt5 qml bugs, in a less disturbing way these were already visible in the xenial AppImage before cherry pick

**Comment by devendrn** [comment]
What is the lowest version that I should target? 5.9?

Also I just noticed the `qt6-reformatted` branch. Should I rebase my qt6 branch to include your commit before my redesign commit?

**Comment by ChristopherHX** [comment]
> What is the lowest version that I should target? 5.9?

Yes qt5.9 is the lowest target version the launcher supports

> Also I just noticed the qt6-reformatted branch. Should I rebase my qt6 branch to include your commit before my redesign commit?

Your qt6 branch is merged, please ignore qt6-reformatted

If you make changes to qt6 rebase your branch on qt6 (squashed merge)
If you make changes to qt5 target the ng-redesign branch

**Comment by ChristopherHX** [comment]
If you can run bookworm appimages then please test them <https://github.com/minecraft-linux/mcpelauncher-manifest/releases/tag/nightly> (The non bookworm variants has the old gui)

**Comment by devendrn** [comment]
I have roughly tested `Minecraft_Bedrock_Launcher-bookworm-x86_64-v0.14.1.296.AppImage`. Everything seems to look and function as expected so far. 

Screenshot_20240417_092207

**Comment by ChristopherHX** [comment]
Thank you for testing the qt6AppImage. I now try to confgure the qt5 AppImage to load the qml resources from disk so I can patch them without rebuilding or installing qt5.9.

**Comment by ChristopherHX** [comment]
Problems should be fixed now, the centered scrollview didn't work correctly. Also the left sidebar buttons lost it's selection state on click.

The centered scrollview now behaves differently on smaller widths and shows a scrollbar again

**Comment by ChristopherHX** [comment]
Merged new design for qt5 as well.

Overlapping gamelog in the cashwindow is postponed for a performance rewrite of that component

**Comment by devendrn** [comment]
Why isn't it possible to use a higher version like Qt5.15 for those AppImages?

**Comment by devendrn** [comment]
I have plans to add more features overtime like animations, overlayed popups, and other subtle improvements. Is it okay if I make PRs for these when they are done?

**Comment by ChristopherHX** [comment]
> Why isn't it possible to use a higher version like Qt5.15 for those AppImages?

Because it is a lot of work for me that's mostly all (still easier for me to support qt5.9 than doing this), this launcher depends on qtwebengine that depends on chromium that has build times over 6hours (the time limit for hosted runners, I could technically built it on my devices once)  in GitHub Actions and AppImages are not the only target using really old qt5

I would prefer qt6.3 (uses cmake) over qt5.15 (uses qmake), since then I'm less far away to drop the qt5 branch.

> I have plans to add more features overtime like animations, overlayed popups, and other subtle improvements. Is it okay if I make PRs for these when they are done?

Feel free do do this, it's great to see someone put some love into the UI.
You can prefer doing it in qt6.3, then I can look into backporting what is possible to the qt5.9 branch. I have been successful by rewriting the qml code of Appmage on the fly to work on qt5.9 and look pretty much like your qt6 code. (takes less time than rewriting my GitHub Actions pipelines to update qt)

**Pull request merged**
